# Generated by Django 4.2.5 on 2023-10-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='img',
            field=models.ImageField(default='liverpool', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
